backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - label: Blog
    name: blog
    slug: '{{slug}}'
    folder: /content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - label: Products
    name: Products
    slug: '{{slug}}'
    folder: /content/products
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'list',
          summary: '{{fields.image}}',
          fields: { label: Image, name: image, widget: image },
        }
